### PR TITLE
Private Endpoint support for Redis and MySQL

### PR DESCRIPTION
**Pull request by claassen**
Adds new plan inputs `private_endpoint_subnet_id` and `private_dns_zone_ids` to support creating Private Endpoints during provisioning.

### CODE REVIEW

**Comment by blgm** [comment]
Hi @claassen, I've pulled these changes locally and run `make run-examples service_name=csb-azure-redis example_name=redis-cache-small`. I get the following error in the CSB log:
```
{"timestamp":"1621951872.746600628","source":"terraform@/tmp/gsb336945938","message":"terraform@/tmp/gsb336945938.terraform execution failed","log_level":2,"data":{"error":"exit status 1","errors":"\nError: Invalid function argument\n\n  on brokertemplate/definition.tf line 54, in locals:\n  54:   private_endpoint_enabled = length(var.private_endpoint_subnet_id) \u003e 0 ? true : false\n    |----------------\n    | var.private_endpoint_subnet_id is null\n\nInvalid value for \"value\" parameter: argument must not be null.\n\n"}}
```

**Comment by claassen** [comment]
Strange, the plan defaults don't seem to work as I expect:

```
- field_name: private_endpoint_subnet_id
    type: string
    details: The ID of the Subnet within which Private Endpoint for the Redis cache will be created.
    default: ""
```

I've added a new commit which should now handle this case.

**Comment by blgm** [comment]
@claassen, I've pulled the latest commit and now the error is slightly different:
```
{"timestamp":"1621962108.249881268","source":"terraform@/tmp/gsb006218118","message":"terraform@/tmp/gsb006218118.terraform execution failed","log_level":2,"data":{"error":"exit status 1","errors":"\nError: Invalid function argument\n\n  on brokertemplate/definition.tf line 54, in locals:\n  54:   private_endpoint_enabled = var.private_endpoint_subnet_id == null || length(var.private_endpoint_subnet_id) \u003e 0 ? true : false\n    |----------------\n    | var.private_endpoint_subnet_id is null\n\nInvalid value for \"value\" parameter: argument must not be null.\n\n"}}
```

**Comment by claassen** [comment]
Can you try now? I've set the input to be an empty string as default. Unfortunately I am unable to run the run-examples test on my local machine to verify myself, I've just been running the Terraform directly where I didn't run into this issue.

**Comment by blgm** [comment]
Another error:
```
{"timestamp":"1622021738.570181131","source":"terraform@/tmp/gsb159303018","message":"terraform@/tmp/gsb159303018.terraform execution failed","log_level":2,"data":{"error":"exit status 1","errors":"\nError: Invalid function argument\n\n  on brokertemplate/definition.tf line 57, in locals:\n  57:   private_endpoint_enabled = length(var.private_endpoint_subnet_id) \u003e 0 ? true : false\n    |----------------\n    | var.private_endpoint_subnet_id is null\n\nInvalid value for \"value\" parameter: argument must not be null.\n\n"}}
```

This feedback loop isn't really working. Out of curiosity, what are the blockers stopping you from running the examples? Is there something we could do to make it easier?

**Comment by claassen** [comment]
We have this thing called zScaler forced on us that makes us have to always use a proxy for build dependencies, otherwise we get cert validation errors. I am able to work around this issue for the psqlcmd and sqlfailover builds by adding a GOPROXY flag in the makefiles, but in a later step I can't get past this error:

```
Status: Downloaded newer image for cfplatformeng/csb:latest
2021/05/26 14:16:01 Packing...
2021/05/26 14:16:01 Using temp directory: /tmp/brokerpak2806316224
2021/05/26 14:16:01 Packing sources...
2021/05/26 14:16:01 	 https://github.com/hashicorp/terraform/archive/v0.12.30.zip -> /tmp/brokerpak2806316224/src/terraform.zip
2021/05/26 14:16:02 error while packing "": Get "https://github.com/hashicorp/terraform/archive/v0.12.30.zip": x509: certificate signed by unknown authority
make: *** [azure-services-*.brokerpak] Error 1
```

I was a able to reproduce the error you are seeing though by explicitly providing a null value for private_endpoint_subnet_id in my .tfvars file. My latest commit should hopefully actually resolve the issue now.

**Comment by claassen** [comment]
@blgm Apologize for the back and forth here, but just following up on this to see if you got a chance to try out the latest change.

**Review by pivotal-marcela-campo — APPROVED** [review]

**Comment by pivotal-marcela-campo** [comment]
@claassen this has been merged and will be included in our next release. The brokerpak release has been tagged if you want to give it a try [1.0.0-rc.40](https://github.com/cloudfoundry-incubator/csb-brokerpak-azure/releases/tag/1.0.0-rc.40)

**Pull request merged**
